SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300

SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin

<VirtualHost *:443>
	SSLEngine on
	# The environments that are running at our partners have /secrets/httpd as the location for the certificate
	# In our environments we use /cert, since a) the `httpd` subdirectory no longer makes a lot of sense, and b) it is easier with acme.sh/Let's Encrypt.
	# For now we support both locations, we may ask ISC at some point to change the host mount to match our environments
	Define SSL_CERT_LOCATION "/secrets/httpd"
	<IfFile "/cert/server.crt">
		Define SSL_CERT_LOCATION "/cert"
	</IfFile>
	SSLCertificateFile "${SSL_CERT_LOCATION}/server.crt"
	SSLCertificateKeyFile "${SSL_CERT_LOCATION}/server.key"
	# HSTS (15768000 seconds = 6 months)
	Header always set Strict-Transport-Security "max-age=15768000"
</VirtualHost>

SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA
SSLHonorCipherOrder     on
SSLCompression          off

SSLUseStapling          on
SSLStaplingResponderTimeout 5
SSLStaplingReturnResponderErrors off
SSLStaplingCache        shmcb:/var/run/ocsp(128000)

SetEnv no-gzip 1