pid ../../temp/nginx.pid;

events {}

http {
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	types {
		application/json map;
		text/javascript mjs;
	}

	access_log ../../temp/nginx-access.log;

	sendfile on;
	tcp_nopush on;

	gzip on;
	gzip_types *;
	gzip_static on;

	types_hash_max_size 4096;
	server_names_hash_bucket_size 128;

	charset utf-8;
	index index.html index.htm;

	server {
		set $home "/home/swdv/";  #TODO

		listen 2280;
		server_name localhost;

		try_files $uri $uri/ $uri.html =404;
		autoindex on;

		# Required for SharedArrayBuffer
		add_header Cross-Origin-Embedder-Policy require-corp;
		add_header Cross-Origin-Opener-Policy same-origin;

    # For development: can store, but always check for newer version
		add_header Cache-Control no-cache;

		root ../../;

		location /.conan2/ {
			alias $home/.conan2/;
		}
		location /emsdk/ {
			alias $home/emsdk/;
		}
		location /emsdk/emscripten/ {
      alias $home/emsdk/upstream/emscripten/;
    }
    # Firefox has trouble finding the right location
    location /weblib/cache/ {
      alias ../../build/wasm32/Debug/cpp/cache/;
    }
	}
}
