
# Configuration for creating a new project

# Fill in at least the following variables:

# Name, e.g. "NOLAI Sandbox", this will become the branding name and watchdog widget title
NEW_PROJECT_NAME=""
# Short slug, this is the name of the repository, e.g. sandbox for "pep/nolai/subdir/sandbox.git"
NEW_PROJECT_SHORT_SLUG=""
# Subgroup path, e.g. "nolai/subdir" for "pep/nolai/subdir/sandbox.git"
NEW_PROJECT_SUBGROUP_PATH=""
# Branch name, e.g. "acc". If any other than "test", "acc" or "prod" are used, make sure to set 
# variables:
#  PEP_PROJECT_TESTING_BRANCH: <branch name>
# or
# variables:
#  PEP_PROJECT_ACCEPTANCE_BRANCH: <branch name>
# manually in the new project .gitlab-ci.yml file
NEW_PROJECT_BRANCH=""
# Acronym, this will be used in short pseudonyms, e.g. "NOLS" for "NOLAI Sandbox
NEW_PROJECT_ACRONYM=""
# Absolute path to the logo file
NEW_PROJECT_LOGO_PATH=""
# Server location, e.g. pep-build1
NEW_PROJECT_SERVER_LOCATION=""

# Optionally, you can change the following variables:

# Group name e.g. pep
NEW_PROJECT_GROUP="pep"
# Medium slug, this is the path and name of the repository, e.g. nolai-subdir-sandbox for "pep/nolai/subdir/sandbox.git"
# It will be used in the project caption
NEW_PROJECT_MEDIUM_SLUG="$(echo "${NEW_PROJECT_SUBGROUP_PATH}" | tr '/' '-')-${NEW_PROJECT_SHORT_SLUG}"
# Full slug, it's named after the medium slug and branch, e.g. "nolai-subdir-sandbox-acc", 
# this will become the server name
NEW_PROJECT_FULL_SLUG="${NEW_PROJECT_MEDIUM_SLUG}-${NEW_PROJECT_BRANCH}"
# Domain name, e.g. pep.cs.ru.nl
NEW_PROJECT_DOMAIN_NAME="pep.cs.ru.nl"
# Gitlab user name (support@pep.cs.ru.nl), used when retrieving images from the repository.
# The corresponding key/token is retrieved from ops
NEW_PROJECT_GITLAB_USER_NAME="support@pep.cs.ru.nl"