#include <pep/accessmanager/tests/TestSuiteGlobalConfiguration.hpp>

// Contents were copied from core/config/projects/gum/accessmanager/GlobalConfiguration.json

const char* TEST_SUITE_GLOBAL_CONFIGURATION =
"{" "\n"
"  \"participant_identifier_formats\": [" "\n"
"    {\"generable\" : {\"prefix\" : \"GUM\", \"digits\" : 10}}," "\n"
"    {\"regex\" : {\"pattern\" : \"[a-zA-Z0-9]{15}\"}}" "\n"
"  ]," "\n"
"\n"
"  \"column_specifications\": [" "\n"
"    { \"column\": \"OnlyPseudonymise\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit1.FMRI\"," "\n"
"    }," "\n"
"    { \"column\": \"OnlyDirectory\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"BothPseudoAndDir\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit1.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Visit1.MRI.Func\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Visit1.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Visit1.MRI.Anat\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Visit1.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Bugs.Visit1.MRI.Func\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit1.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Bugs.Visit1.MRI.Anat\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit1.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Bugs.Visit2.MRI.Func\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit2.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Bugs.Visit2.MRI.Anat\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Bugs.Visit2.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Visit3.MRI.Func\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Visit3.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }," "\n"
"    { \"column\": \"Visit3.MRI.Anat\"," "\n"
"      \"associated_short_pseudonym_column\": \"ShortPseudonym.Visit3.FMRI\"," "\n"
"      \"requires_directory\": true" "\n"
"    }" "\n"
"  ]," "\n"
"\n"
"  \"study_contexts\": [" "\n"
"    { \"id\": \"GUM\" }," "\n"
"    { \"id\": \"BUGS\" }" "\n"
"  ]," "\n"
"\n"
"  \"short_pseudonyms\": [" "\n"
"    {\"column\": \"ShortPseudonym.Castor.Reports\", \"prefix\": \"GUMRE\", \"length\": 5," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomreportsa\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"    {\"column\": \"ShortPseudonym.Castor.ECG\", \"prefix\": \"GUMEC\", \"length\": 5, \"description\": \"ECG findings\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis1ecga\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"STUDY\"," "\n"
"          \"data_column\": \"Castor.ECG\"," "\n"
"          \"import_study_slug\": \"pomvis1ecgp\"," "\n"
"          \"immediate_partial_data\": true" "\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Castor.DeviceDeficiency\", \"prefix\": \"GUMDD\", \"length\": 5, \"description\": \"Device deficiencies\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomdevidefa\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"    {\"column\": \"ShortPseudonym.Castor.EndOfStudy\", \"prefix\": \"GUMES\", \"length\": 5, \"description\": \"End of Study Survey\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"cHR2JwNU8M99vWEEXQgJ5n\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"\n"
"\n"
"    {\"column\": \"ShortPseudonym.Visit1.FMRI\", \"prefix\": \"GUM1FM\", \"length\": 5, \"description\": \"fMRI\"}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.ECG\", \"prefix\": \"GUM1EC\", \"length\": 5, \"stickers\": 1, \"suppress_additional_stickers\": true}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.PBMC\", \"prefix\": \"GUM1PM\", \"length\": 5, \"stickers\": 4}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Plasma\", \"prefix\": \"GUM1PL\", \"length\": 5, \"stickers\": 4}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.DNA\", \"prefix\": \"GUM1DN\", \"length\": 5, \"stickers\": 1}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.RNA\", \"prefix\": \"GUM1RN\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Serum\", \"prefix\": \"GUM1SE\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.CSF\", \"prefix\": \"GUM1CS\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Stool\", \"prefix\": \"GUM1ST\", \"length\": 5, \"stickers\": 2}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.QAVideo\", \"prefix\": \"GUM1VD\", \"length\": 5, \"description\": \"QA Video\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"dQ4onnU5YGztyWKptKzRqG\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"REPEATING_DATA\"," "\n"
"          \"data_column\": \"Castor.Updrs1\"," "\n"
"          \"import_study_slug\": \"egtjShrkrotkUPgFoGaoY7\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Castor.Visit\", \"prefix\": \"GUM1VS\", \"length\": 5," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis1crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"STUDY\"," "\n"
"          \"data_column\": \"Castor.Visit1\"," "\n"
"          \"import_study_slug\": \"pomvis1crfp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.FoodQuestionnaire\", \"prefix\": \"GUM1FQ\", \"length\": 5, \"description\": \"Food Questionnaire\"}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Castor.HomeQuestionnaires\", \"prefix\": \"GUM1HQ\", \"length\": 5, \"description\": \"Home questionnaires\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis1homa\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"SURVEY\"," "\n"
"          \"data_column\": \"Castor.HomeQuestionnaires1\"," "\n"
"          \"import_study_slug\": \"pomvis1homp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit1.Castor.StoolQuestionnaire\", \"prefix\": \"GUM1SQ\", \"length\": 5, \"description\": \"Stool questionnaire\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomsto1crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"\n"
"    {\"column\": \"ShortPseudonym.Visit2.ECG\", \"prefix\": \"GUM2EC\", \"length\": 5, \"stickers\": 1, \"suppress_additional_stickers\": true}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Plasma\", \"prefix\": \"GUM2PL\", \"length\": 5, \"stickers\": 4}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.RNA\", \"prefix\": \"GUM2RN\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Serum\", \"prefix\": \"GUM2SE\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Stool\", \"prefix\": \"GUM2ST\", \"length\": 5, \"stickers\": 2}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.QAVideo\", \"prefix\": \"GUM2VD\", \"length\": 5, \"description\": \"QA Video\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"cevfptZSSog4Jq3AjY76ag\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"REPEATING_DATA\"," "\n"
"          \"data_column\": \"Castor.Updrs2\"," "\n"
"          \"import_study_slug\": \"PwT86vrJKN762vdMhRGizJ\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Castor.Visit\", \"prefix\": \"GUM2VS\", \"length\": 5," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis2crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"STUDY\"," "\n"
"          \"data_column\": \"Castor.Visit2\"," "\n"
"          \"import_study_slug\": \"pomvis2crfp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.FoodQuestionnaire\", \"prefix\": \"GUM2FQ\", \"length\": 5, \"description\": \"Food Questionnaire\"}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Castor.HomeQuestionnaires\", \"prefix\": \"GUM2HQ\", \"length\": 5, \"description\": \"Home questionnaires\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis2homa\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"SURVEY\"," "\n"
"          \"data_column\": \"Castor.HomeQuestionnaires2\"," "\n"
"          \"import_study_slug\": \"pomvis2homp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit2.Castor.StoolQuestionnaire\", \"prefix\": \"GUM2SQ\", \"length\": 5, \"description\": \"Stool questionnaire\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomsto2crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"\n"
"    {\"column\": \"ShortPseudonym.Visit3.FMRI\", \"prefix\": \"GUM3FM\", \"length\": 5, \"description\": \"fMRI\"}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.ECG\", \"prefix\": \"GUM3EC\", \"length\": 5, \"stickers\": 1, \"suppress_additional_stickers\": true}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Plasma\", \"prefix\": \"GUM3PL\", \"length\": 5, \"stickers\": 4}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.RNA\", \"prefix\": \"GUM3RN\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Serum\", \"prefix\": \"GUM3SE\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Stool\", \"prefix\": \"GUM3ST\", \"length\": 5, \"stickers\": 1}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.CSF\", \"prefix\": \"GUM3CS\", \"length\": 5, \"stickers\": 3}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.QAVideo\", \"prefix\": \"GUM3VD\", \"length\": 5, \"description\": \"QA Video\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"BhnRRqzRMBJbmeiBecP3jg\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"REPEATING_DATA\"," "\n"
"          \"data_column\": \"Castor.Updrs3\"," "\n"
"          \"import_study_slug\": \"mtidLy9N9Sd9SKFMRRNzHX\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Castor.Visit\", \"prefix\": \"GUM3VS\", \"length\": 5," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomvis3crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"STUDY\"," "\n"
"          \"data_column\": \"Castor.Visit3\"," "\n"
"          \"import_study_slug\": \"pomvis3crfp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.FoodQuestionnaire\", \"prefix\": \"GUM3FQ\", \"length\": 5, \"description\": \"Food Questionnaire\"}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Castor.HomeQuestionnaires\", \"prefix\": \"GUM3HQ\", \"length\": 5, \"description\": \"Home questionnaires\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"u5BUTAmZfTsqajjjNuzRo\"," "\n"
"        \"site_abbreviation\": \"umcn\"," "\n"
"        \"storage\": {" "\n"
"          \"study_type\": \"SURVEY\"," "\n"
"          \"data_column\": \"Castor.HomeQuestionnaires3\"," "\n"
"          \"import_study_slug\": \"pomvis3homp\"\n"
"        }}}," "\n"
"    {\"column\": \"ShortPseudonym.Visit3.Castor.StoolQuestionnaire\", \"prefix\": \"GUM3SQ\", \"length\": 5, \"description\": \"Stool questionnaire\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pomsto3crfa\"," "\n"
"        \"site_abbreviation\": \"umcn\"}}," "\n"
"\n"
"\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.DNA\", \"prefix\": \"BUGDN\", \"length\": 5, \"stickers\": 1}," "\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.Serum\", \"prefix\": \"BUGSE\", \"length\": 5, \"stickers\": 1}," "\n"
"\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.Castor.Reports\", \"prefix\": \"BUGRE\", \"length\": 5, \"description\": \"Castor\"," "\n"
"      \"castor\": {" "\n"
"        \"study_slug\": \"pitreportsacceptance\"," "\n"
"        \"site_abbreviation\": \"DCCN\"," "\n"
"        \"storage\": [" "\n"
"          { \"study_type\": \"SURVEY\"," "\n"
"            \"data_column\": \"Bugs.Castor.HomeQuestionnaires\"," "\n"
"            \"import_study_slug\": \"pitreportsproduction\"\n"
"          }," "\n"
"          { \"study_type\": \"STUDY\"," "\n"
"            \"data_column\": \"Bugs.Castor.Visit\"," "\n"
"            \"import_study_slug\": \"pitreportsproduction\"," "\n"
"            \"immediate_partial_data\": true" "\n"
"          }" "\n"
"        ]}}," "\n"
"\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.Visit1.FMRI\", \"prefix\": \"BUG1MR\", \"length\": 5, \"description\": \"fMRI\"}," "\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.Visit1.SerialChoice\", \"prefix\": \"BUG1CH\", \"length\": 5, \"description\": \"Serial Choice Task\"}," "\n"
"    {\"study_context\": \"BUGS\", \"column\": \"ShortPseudonym.Bugs.Visit2.FMRI\", \"prefix\": \"BUG2MR\", \"length\": 5, \"description\": \"fMRI\"}" "\n"
"  ]," "\n"
"\n"
"  \"short_pseudonym_errata\": [" "\n"
"    {\"value\": \"GUM1ST1234567\", \"column\": \"ShortPseudonym.Visit1.Serum\"}" "\n"
"  ]," "\n"
"  " "\n"
"  \"user_pseudonym_format\":" "\n"
"    {\"prefix\" : \"GUMU\", \"minLength\" : 1, \"length\" : 16}," "\n"
"\n"
"  \"additional_stickers\": [" "\n"
"    {\"visit\": 1, \"column\": \"ShortPseudonym.Visit2.Stool\", \"stickers\": 1}," "\n"
"    {\"visit\": 1, \"column\": \"ShortPseudonym.Visit2.Castor.StoolQuestionnaire\", \"stickers\": 0}," "\n"
"    {\"visit\": 2, \"column\": \"ShortPseudonym.Visit3.Stool\", \"stickers\": 1}," "\n"
"    {\"visit\": 2, \"column\": \"ShortPseudonym.Visit3.Castor.StoolQuestionnaire\", \"stickers\": 0}" "\n"
"  ]," "\n"
"\n"
"  \"devices\": [" "\n"
"    {\"column\": \"DeviceHistory\",        \"serial_number_format\": \"[a-zA-Z0-9]{16}\", \"description\": \"GUM horloge\",     \"tooltip\": \"Voer 16 karakters in bestaande uit hoofdletters of cijfers\"}," "\n"
"    {\"column\": \"Bugs.DeviceHistory\", \"serial_number_format\": \"[a-zA-Z0-9]{16}\", \"description\": \"BUGS horloge\", \"tooltip\": \"Voer 16 karakters in bestaande uit hoofdletters of cijfers\", \"study_context\": \"BUGS\"}" "\n"
"  ]," "\n"
"\n"
"  \"assessors\": [" "\n"
"    {\"id\": 1, \"name\": \"Popeye the Sailor Man\"}," "\n"
"    {\"id\": 2, \"name\": \"Mickey Mouse\", \"study_contexts\": [\"GUM\"]}," "\n"
"    {\"id\": 3, \"name\": \"Donald Duck\", \"study_contexts\": [\"BUGS\"]}," "\n"
"    {\"id\": 4, \"name\": \"Skeletor\", \"study_contexts\": [\"GUM\", \"BUGS\"]}" "\n"
"  ]" "\n"
"}" "\n"
;