#pragma once

#include <pep/accessmanager/AccessManagerMessages.hpp>
#include <pep/crypto/CryptoSerializers.hpp>

namespace pep {

PEP_DEFINE_EMPTY_SERIALIZER(GlobalConfigurationRequest);

PEP_DEFINE_CODED_SERIALIZER(IndexedTicket2);

PEP_DEFINE_ENUM_SERIALIZER(KeyBlindMode);

PEP_DEFINE_CODED_SERIALIZER(KeyRequestEntry);
PEP_DEFINE_CODED_SERIALIZER(EncryptionKeyRequest);
PEP_DEFINE_SIGNED_SERIALIZATION(EncryptionKeyRequest);
PEP_DEFINE_CODED_SERIALIZER(EncryptionKeyResponse);

PEP_DEFINE_CODED_SERIALIZER(ColumnAccessRequest);
PEP_DEFINE_SIGNED_SERIALIZATION(ColumnAccessRequest);
PEP_DEFINE_CODED_SERIALIZER(ColumnAccessResponse);

PEP_DEFINE_CODED_SERIALIZER(ParticipantGroupAccessRequest);
PEP_DEFINE_SIGNED_SERIALIZATION(ParticipantGroupAccessRequest);
PEP_DEFINE_CODED_SERIALIZER(ParticipantGroupAccessResponse);

PEP_DEFINE_ENUM_SERIALIZER(CrudAction);
PEP_DEFINE_CODED_SERIALIZER(ColumnNameMappingRequest);
PEP_DEFINE_SIGNED_SERIALIZATION(ColumnNameMappingRequest);
PEP_DEFINE_CODED_SERIALIZER(ColumnNameMappingResponse);

}
