variables:
  PEP_FOSS_REPO_DIR: pep
  PEP_PROJECT_DEVELOPMENT_BRANCH: main
  PEP_PROJECT_TESTING_BRANCH: test
  PEP_PROJECT_ACCEPTANCE_BRANCH: acc
  PEP_PROJECT_PRODUCTION_BRANCH: prod

  DATA_SYNC_SOURCE_BRANCH: prod
  DATA_SYNC_TARGET_BRANCH: acc